# Generated by Django 3.2.8 on 2021-10-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211022_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile_default.png', upload_to='profile_pics'),
        ),
    ]
